<?php

namespace CombatantsBundle\Repository;

/**
 * BadgesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadgesRepository extends \Doctrine\ORM\EntityRepository
{
}
