<?php

namespace CombatantsBundle\Repository\Combatants;

/**
 * DefenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefenseRepository extends \Doctrine\ORM\EntityRepository
{
}
