<?php

namespace CombatantsBundle\Repository\Combatants;

/**
 * HealthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HealthRepository extends \Doctrine\ORM\EntityRepository
{
}
