<?php

namespace CombatantsBundle\Repository\Combatants;

/**
 * LuckRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LuckRepository extends \Doctrine\ORM\EntityRepository
{
}
