<?php

namespace CombatantsBundle\Repository\Combatants;

/**
 * SpeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeedRepository extends \Doctrine\ORM\EntityRepository
{
}
