<?php

namespace CombatantsBundle\Repository\Combatants;

/**
 * StrengthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StrengthRepository extends \Doctrine\ORM\EntityRepository
{
}
