<?php

namespace CombatantsBundle\Repository\Combatants;

/**
 * TypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypesOfCombatantsRepository extends \Doctrine\ORM\EntityRepository
{
}
